111 update notification modules - adding option user_groups
T-Systems-MMS/ansible-collection-icinga-director pull request #112
Opened 2021-02-13 01:30 UTC by sgruber94

Adding option user_groups for Notifications

2021-02-13 12:50 UTC, sgruber94 commented
Some Sanity Checks will not work, because I can't create a user group automatic ( atm.)

2021-02-15 08:32 UTC, rndmh3ro commented
Hi @sgruber94,

thanks for this PR!

Two things: 
* Can you name the variable consistently, please? It should be `user_groups`
* After changing the code in the python module, you do not need to manually alter the tests and examples. Instead follow the steps mentioned here: https://github.com/T-Systems-MMS/ansible-collection-icinga-director#updating-the-tests-and-examples

2021-02-15 08:49 UTC, sgruber94 commented
I updated already all vars, but didn't push the version
thanks for pointing to the manual. 
I will use that in future :)

-> user_groups will be failing in the tests every time because no user_groups are created automatically

Should i  add Version "added string" or something else?

2021-02-15 09:12 UTC, rndmh3ro commented
> I updated already all vars, but didn't push the version

Thanks, however it should be `user_groups`, not `users_groups`.

> Should i add Version "added string" or something else?

Good idea, please add `version_added: '1.16.0'`.

2021-02-15 12:21 UTC, rndmh3ro requested changes

2021-02-15 12:21 UTC, rndmh3ro commented on plugins/modules/icinga_notification.py
> +      - User Group that should be notified by this notification.
```suggestion
      - User Groups that should be notified by this notification.
```

2021-02-15 12:21 UTC, rndmh3ro commented on plugins/modules/icinga_notification_template.py
> +      - User Group that should be notified by this notification.
```suggestion
      - User Groups that should be notified by this notification.
```

2021-02-15 12:21 UTC, rndmh3ro commented on plugins/modules/icinga_notification.py
> +        "users_groups": module.params["users_groups"],
```suggestion
        "user_groups": module.params["user_groups"],
```

2021-02-15 12:21 UTC, rndmh3ro commented on plugins/modules/icinga_notification.py
> +        users_groups=dict(type="list", elements="str", required=False),
```suggestion
        user_groups=dict(type="list", elements="str", required=False),
```

2021-02-15 12:21 UTC, rndmh3ro commented on plugins/modules/icinga_notification_template.py
> +        "user_groups": module.params["users_groups"],
```suggestion
        "user_groups": module.params["user_groups"],
```

2021-02-15 12:33 UTC, sgruber94 commented
@rndmh3ro  please keep in mind, that this  pull request will  break  the automated test ( usergroup OnCall) is not created automatically

2021-02-15 12:39 UTC, rndmh3ro commented
> @rndmh3ro please keep in mind, that this pull request will break the automated test ( usergroup OnCall) is not created automatically

Thanks, will do! :)

2021-02-15 12:40 UTC, rndmh3ro commented on plugins/modules/icinga_notification_template.py
> +        users_groups=dict(type="list", elements="str", required=False),
```suggestion
        user_groups=dict(type="list", elements="str", required=False),
```

2021-02-15 15:15 UTC, rndmh3ro commented
Thanks, looks good now.
As soon as we have a  module for group-creation, I can merge this.

2021-02-15 21:01 UTC, rndmh3ro commented
Hey @sgruber94,

we added support for the user_group module. Can you please merge the master-branch into your branch?

2021-02-15 21:20 UTC, sgruber94 commented
@rndmh3ro  master branch merged. Also found one typo. And fixed that.

2021-02-16 07:13 UTC, rndmh3ro approved these changes

2021-02-16 07:15 UTC, merged

2021-02-16 07:16 UTC, rndmh3ro commented
Thank you!