add option to append arguments to all modules
T-Systems-MMS/ansible-collection-icinga-director pull request #153
Opened 2021-11-25 07:37 UTC by rndmh3ro

2021-11-25 07:59 UTC, schurzi commented
small nitpick: this PR addad a *.pyc file. I don'T want these files in the repo, can you add a gitignore and remove the file?

2021-11-26 09:13 UTC, rndmh3ro commented
Thanks, @schurzi, fixed.

The two failing tests are unrelated and will be fixed separately.

2021-11-26 14:33 UTC, schurzi commented on plugins/modules/icinga_timeperiod_template.py
> +    if module.params["append"]:
I had a really hard time understanding this piece. In my understanding you are discarding the regular `data` hash, that has all values stored and you are creating a new one, that has only the intersection of keys, that are in the old `data` hash and from `module.params`. 

You do that to only include new parameter specified by the user. I thought our issue here is, that defaults from the module spec get also added in the default `data` hash. How is that solved here?

Also I hold a pretty big issue here, because we are initializing the same data twice. I don't like that. I would favor a solution, that merges this with the data initialization above.

What do you think about using intesections on the keys of `module.params` and a list of keys that we specify. (like https://stackoverflow.com/questions/18554012/intersecting-two-dictionaries) and then setting all values, that are in the intersection.

like this (pseudocode):
```python
data_keys = ["zone", "imports", "ranges", ...]

foreach key in module.params.keys() & data_keys
  data[key] = module.params[key]
```

2021-11-28 09:53 UTC, schurzi commented
So I spend some more time looking at this. I generally like the idea, but there are some things I really don't like. I think they are solvable and I can add the code to solve them, if you like.

The two things are:
- we are dropping `required_if` for required options. I don't want to do that. How about we only drop the `required_if` when we are in append mode?
- The separate options parsing for the default case and the append case bug me. I already posted a possible solution to that. But I still don't understand how the different approach in option assignment in your (and my) solution solves the problem with default overrides.

2021-11-29 09:20 UTC, rndmh3ro commented on plugins/modules/icinga_timeperiod_template.py
> +    if module.params["append"]:
Thanks for your input? What do you think about this solution?

```
    data_keys = [
        "object_name",
        "display_name",
        "groups",
        "imports",
        "disabled",
        "address",
        "address6",
        "zone",
        "vars",
        "check_command",
        "notes",
        "notes_url",
        "has_agent",
        "master_should_connect",
        "accept_config",
        "command_endpoint",
    ]

    data = {}

    if module.params["append"]:
        for k in data_keys:
            if module.params[k]:
                data[k] = module.params[k]
    else:
        for k in data_keys:
            data[k] = module.params[k]


    data["object_type"] = "object"
```

Now the data-dict only gets defined once and not overwritten.

> You do that to only include new parameter specified by the user. I thought our issue here is, that defaults from the module spec get also added in the default data hash. How is that solved here?

Our issue is that every value (even empty or None) gets added to the data hash, thus overwriting everything. With the new code, this doesn't happen anymore.
However the defaults are still applied and would be applied with `append: true` even if not defined. There's no easy way to fix that, so I'll add it as a caveat into the docs.

2021-11-29 13:50 UTC, schurzi commented on plugins/modules/icinga_timeperiod_template.py
> +    if module.params["append"]:
Ok, then I understood it right. WE need to document this behavior, since this might be unexpected by the user.

I also think, that we do not need the additional `append` flag. As far as I can see, there is no difference between a normal apply and an append, when we generate the dict via the for loop.

So this should work in any case:
```python
    data_keys = [
        "object_name",
        "display_name",
        "groups",
        "imports",
        "disabled",
        "address",
        "address6",
        "zone",
        "vars",
        "check_command",
        "notes",
        "notes_url",
        "has_agent",
        "master_should_connect",
        "accept_config",
        "command_endpoint",
    ]

    data = {}

    for key in module.params.keys() & data_keys:
        data[key] = module.params[key]

    data["object_type"] = "object"
```

If we are building the intersection of our defined `data_keys` and the user supplied `module.params` then there are only user defined values and our defaults present. That is exactly what we want in any case. I see no need for a distinction.

2021-11-29 14:32 UTC, rndmh3ro commented on plugins/modules/icinga_timeperiod_template.py
> +    if module.params["append"]:
We do need that append-option.

In this code-block the data from the undefined module.params are set to `""` and sent to the server, thus "emptying" existing values. 

```
    for key in module.params.keys() & data_keys:
        data[key] = module.params[key]
```

In this code-block the data from the undefined module.params are skipped entirely (and thus not send to the server):
```
    if module.params["append"]:
        for key in data_keys:
            if module.params[key]:
               data[key] = module.params[k]
```

Consider this play:
```
---
- name: Create timeperiod
  t_systems_mms.icinga_director.icinga_timeperiod:
    state: present
    url: "{{ icinga_url }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    object_name: '24/7'
    imports:
      - "timeperiod_template"
    ranges:
      monday: "00:00-23:59"
      tuesday: "00:00-23:59"
      wednesday: "00:00-23:59"
      thursday: "00:00-23:59"
      friday: "00:00-23:59"
      saturday: "00:00-23:59"
      sunday: "00:00-23:59"


- name: append displayname to timeperiod
  t_systems_mms.icinga_director.icinga_timeperiod:
    state: present
    url: "{{ icinga_url }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    object_name: '24/7'
    display_name: '24/7'

- name: Update timeperiod
  t_systems_mms.icinga_director.icinga_timeperiod:
    state: present
    url: "{{ icinga_url }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    object_name: '24/7'
```

With your code, this happens:
![grafik](https://user-images.githubusercontent.com/3198961/143884418-7f2ba2e2-2c2a-49b1-86dc-4b201dd7d54e.png)
![grafik](https://user-images.githubusercontent.com/3198961/143884475-2b2b9e80-d697-45eb-a032-c5dd80a9574a.png)
![grafik](https://user-images.githubusercontent.com/3198961/143884639-266842da-0233-4468-a41a-4cb48e759a50.png)


With my code:
![grafik](https://user-images.githubusercontent.com/3198961/143885065-e5e9f6e8-a7b5-4c0d-964f-c0b279acb6a7.png)
![grafik](https://user-images.githubusercontent.com/3198961/143885095-685e25e0-c73e-4de2-a198-c3db8adf4e11.png)
![grafik](https://user-images.githubusercontent.com/3198961/143885150-7e187b44-b8c8-4c0b-afea-67847da9e74b.png)

2021-11-29 16:58 UTC, schurzi commented on plugins/modules/icinga_timeperiod_template.py
> +    if module.params["append"]:
ahh, I see. So Ansible sets all parameters to `None`, even if they are not specified by the user. In the normal case we need to honor the `None` to allow for deletion of Parameters, but when appending, we need to ignore `None` parameters.

In that case I like your proposed solution and we only need some documentation for the behavior when appending.

2021-11-30 17:20 UTC, schurzi requested changes
Documentation of behavior with `append` needs to be added.

Also I'm not sure, if adding the `required_if` to a already initialized module works. Maybe we need to initialize the module twice? Or we need some other way to get the parameter before initializing the `AnsibleModule`?

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_service_template.py
> +    data["object_type"] = "template"
```suggestion
    else:
        for k in data_keys:
            data[k] = module.params[k]

    data["object_type"] = "template"
```

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_host.py
> +        module.required_if = [("state", "present", ["imports"])]
```suggestion
```

not sure if this woks the way you intended, the `AnsibleModule` is already initialized at this point and changes to this parameter will most likely be ignored.

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_host.py
> +      - Required if I(state) is C(present).
```suggestion
```

Also delete this, if change to `required_if` further down is correct.

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_notification.py
> +      - Required if I(state) is C(present).
```suggestion
```

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_notification.py
> +        module.required_if = [("state", "present", ["apply_to", "imports"])]
```suggestion
```

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_scheduled_downtime.py
> +      - Required if I(state) is C(present).
```suggestion
```

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_scheduled_downtime.py
> +      - Required if I(state) is C(present).
```suggestion
```

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_scheduled_downtime.py
> +      - Required if I(state) is C(present).
```suggestion
```

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_scheduled_downtime.py
> +      - Required if I(state) is C(present).
```suggestion
```

2021-11-30 17:20 UTC, schurzi commented on plugins/modules/icinga_scheduled_downtime.py
> +
```suggestion
```

2021-12-02 19:23 UTC, schurzi commented on plugins/modules/icinga_host.py
> +        module.required_if = [("state", "present", ["imports"])]
good idea.

2021-12-02 19:24 UTC, schurzi commented on plugins/modules/icinga_host.py
> +      - Required if I(state) is C(present).
My thought was, when we remove the `required_if` down in the code, the doc linter will complain, that the docs don't match the code. If that is not the case, we can gladly keep the docs as they are now.

2021-12-03 08:33 UTC, rndmh3ro commented on plugins/modules/icinga_host.py
> +      - Required if I(state) is C(present).
The doc-linter will only complain, if we use `required: true` in the docs and `required_if`. If we only change the description, the linter won't complain.

2021-12-03 08:35 UTC, schurzi commented on plugins/modules/icinga_host.py
> +      - Required if I(state) is C(present).
oh nice, I thought it also checks `required_if`. Then by all means, leave the documentation like this.

2021-12-03 10:23 UTC, schurzi approved these changes

2021-12-03 10:28 UTC, merged