Added missing fields to 'icinga_host' and 'icinga_host_template'
T-Systems-MMS/ansible-collection-icinga-director pull request #158
Opened 2022-03-13 20:54 UTC by HeikoNeblung

This PR will add all the fields mentioned in #59 by @rndmh3ro

Added mising properties:

* enable_notifications
* enable_active_checks
* enable_passive_checks
* enable_event_handler
* enable_flapping
* enable_perfdata
* volatile
* check_period
* check_timeout
* flapping_threshold_high
* flapping_threshold_low
* icon_image
* icon_image_alt

to modules 'icinga_host' and 'icinga_host_template'

2022-03-18 07:07 UTC, rndmh3ro requested changes
The integration tests fail, because two parameters are missing. You need to make sure that a new parameter is at four places in the module:
- docs
- examples
- twice in the code

2022-03-18 07:07 UTC, rndmh3ro commented on plugins/modules/icinga_host.py
>      )
These are missing here (and below and also in the host template):
```
max_check_attempts: 3
retry_interval: "1m"
```

2022-03-18 07:09 UTC, rndmh3ro commented
Also the linting fails. You can run this manually after installing tox by entering: `tox -elinters`

2022-03-18 08:39 UTC, HeikoNeblung commented on plugins/modules/icinga_host.py
>      )
I added the two lines and hope you don't mind reordering them. I think it makes the code more maintainable.

2022-03-19 13:35 UTC, rndmh3ro commented
After https://github.com/T-Systems-MMS/ansible-collection-icinga-director/pull/159 is merged, can you please rebase your PR on master? Then all tests will hopefully pass.

Also please try to separate formatting changes from code-changes next time. :) Otherwise its hard to see what you added and what only changed in the sorting..

2022-03-20 19:41 UTC, HeikoNeblung commented
Sorry for mixing things up. I just wanted to keep the history clean.
Maybe the `tox -elinters` run is a thing to put in CONTRIBUTION.md?

2022-03-28 14:11 UTC, merged

2022-03-28 14:17 UTC, rndmh3ro commented
Thanks for this PR!

>  Maybe the tox -elinters run is a thing to put in CONTRIBUTION.md?

Thanks here, too. I updated it with the information from the readme:
https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/CONTRIBUTING.md