Add Icinga Deploy handler and module
T-Systems-MMS/ansible-collection-icinga-director pull request #205
Opened 2023-03-23 11:38 UTC by flkhndlr

This PR adds a module and handler to trigger a deployment of the Icinga config. Tasks are updated to call the handler.
The default behavior is not changed, so that current users are not confronted with changes in execution.

I'm not sure how to integrate testing for the handler and how to document the usage in a correct way.
Thanks in advance.

This PR resolves Part of #90.

2023-04-24 09:21 UTC, rndmh3ro requested changes

2023-05-04 11:08 UTC, flkhndlr commented on plugins/modules/icinga_deploy.py
> +    def create(self):
yes, now represented in extra Object

2023-05-04 11:09 UTC, flkhndlr commented on plugins/modules/icinga_deploy.py
> +  - This module supports check mode.
removed

2023-05-04 11:11 UTC, flkhndlr commented on plugins/modules/icinga_deploy.py
> +class Deployment(Icinga2APIObject):
I tried to make sure, that only the create Function can be called for this object. But thats the completly the wrong way.

2023-05-04 11:11 UTC, flkhndlr commented on plugins/modules/icinga_deploy.py
> +  register: result
no, removed

2023-05-04 19:02 UTC, rndmh3ro requested changes

2023-05-09 07:24 UTC, flkhndlr commented on plugins/modules/icinga_deploy_info.py
> +        config=object_list["data"],
Thats a good idea, but one thing I noticed was, that the automatic testgeneration wants "objects" as the key. So I changed it to objects rather than active_configuration. If we want to update the testgeneration, I'm open to it :)

2023-05-22 12:21 UTC, merged