allow using whitespaces in object names
T-Systems-MMS/ansible-collection-icinga-director pull request #55
Opened 2020-10-23 21:48 UTC by schurzi

2020-10-23 21:49 UTC, schurzi commented
fixes #52

2020-10-25 20:34 UTC, rndmh3ro requested changes

2020-10-25 20:34 UTC, rndmh3ro commented on plugins/module_utils/icinga.py
> +from ansible.module_utils._text import to_text
Looking at the module here: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/_text.py
It says `.. warn:: Use ansible.module_utils.common.text.converters instead.`

2020-10-25 20:34 UTC, rndmh3ro commented on tests/integration/targets/icinga/roles/icinga/tasks/special_whitespace.yml
> +---
I don't want to manually manage tests (manually handling this file is enough: `tests/integration/targets/icinga/roles/icinga/tasks/main.yml`).

Can you please add this example (or change the existing one so it contains whitespace) into the examples here: `plugins/modules/icinga_service.py`? We could use a "minimal" example with only the required fields and whitespace.

2020-10-26 10:25 UTC, schurzi commented on plugins/module_utils/icinga.py
> +from ansible.module_utils._text import to_text
that's funny, I took this piece of code from ansible-galaxy XD

2020-10-26 10:25 UTC, schurzi commented on plugins/module_utils/icinga.py
> +from ansible.module_utils._text import to_text
https://github.com/ansible/ansible/blob/3e9943bc5e7a9cd393757aa8100d7fed80bd316e/lib/ansible/galaxy/api.py

2020-10-26 11:44 UTC, rndmh3ro approved these changes

2020-10-26 11:44 UTC, merged